### ISSUE TITLE
a case-insensitive fork

### ISSUE THREAD

**Issue by abelew** [peterblattmann/SWATH2stats#1]
Greetings,
  I recently found that for whatever new version of openms/pyprophet/tric, one or more of the columns in my tsv input to SWATH2stats changed the capitalization of some column names.

  In response, I decided to modify SWATH2stats rather than my input file and so I forked the code and merrily hacked away.  I have not changed anything substantive (I think); but made all the columns case-insensitive via tolower(), and therefore all the places which query the columns.  As I was doing this, I gradually filled in some roxygen docstrings.  Only today I realized I should probably have written and asked before messing with your codebase; so I am writing now,  though belatedly.

  The changes I made are in the abelew/SWATH2stats repository; I just committed the docstring changes.  If the modifications I made are not too obnoxious, I would be happy to rebase to your current state and send a pull request.

  I hope you are doing well.

**Comment by peterblattmann** [comment]
Dear Ashton, 

 

Sorry about my very late reply and I’m not sure if you already got a reply by me (I just found my original reply in my draft folder but it was not sent)?

 

Thank you very much for your e-mail and I will have a look in the next weeks on what you did and integrate all the changes I think make sense, if this is fine with you? It is great that you spend so much time on this!

 

Best regards

 

Peter

**Comment by peterblattmann** [comment]
Thanks again @abelew for the contribution including the PR #2 and #3! 
The move to roxygen has been commit in v1.19.1 (https://github.com/peterblattmann/SWATH2stats/commit/56f56c8a0e5e6fce52e8fafaeb2ce3eeff97a9c2)
